---
- name: full image of load balancing
  docker_image:
    name: "{{ lb_image_name }}"
    tag: "{{ lb_image_tag }}"
    source: pull

- name: copy nginx config file to vps1
  copy:
    src: nginx_web.conf
    dest: /etc/nginxlba/
    when: inventory_hostname == "vps1"

- name: copy nginx config file to vps2
  copy:
    src: nginx_api.conf
    dest: /etc/nginxlba/
    when: inventory_hostname == "vps2"

- name: run container for load balancing
  docker_container:
    name: "{{ lb_container_name }}"
    image: "{{ lb_image_name }}:{{ lb_image_tag }}"
    restart_policy: unless-stopped
    ports:
      - 80:80
    volumes:
      - /etc/nginxlba/nginx.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]